"""init

Revision ID: 50e8301c8d5d
Revises: 
Create Date: 2026-07-05 00:01:49.289635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e8301c8d5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('wali_kelas_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mata_pelajaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ppdb_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_anak', sa.String(length=255), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=255), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=1), nullable=False),
    sa.Column('nama_ayah', sa.String(length=255), nullable=True),
    sa.Column('nama_ibu', sa.String(length=255), nullable=True),
    sa.Column('email_orang_tua', sa.String(length=255), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('kelompok_dipilih', sa.Enum('KELOMPOK_BERMAIN', 'TK_A', 'TK_B', name='kelompok_enum'), nullable=False),
    sa.Column('tahun_ajaran', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DITERIMA', 'DITOLAK', name='ppdb_status'), nullable=False),
    sa.Column('catatan_admin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'GURU', 'SISWA', 'ORANG_TUA', name='user_role'), nullable=False),
    sa.Column('nis', sa.String(length=50), nullable=True),
    sa.Column('nip', sa.String(length=50), nullable=True),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('absensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('guru_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('HADIR', 'IZIN', 'SAKIT', 'ALPA', name='status_absensi_enum'), nullable=False),
    sa.ForeignKeyConstraint(['guru_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['siswa_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_absensi_siswa_id'), 'absensi', ['siswa_id'], unique=False)
    op.create_table('jadwal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('mata_pelajaran_id', sa.Integer(), nullable=False),
    sa.Column('guru_id', sa.Integer(), nullable=False),
    sa.Column('hari', sa.Enum('SENIN', 'SELASA', 'RABU', 'KAMIS', 'JUMAT', 'SABTU', name='hari_enum'), nullable=False),
    sa.Column('jam_mulai', sa.Time(), nullable=False),
    sa.Column('jam_selesai', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['guru_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mata_pelajaran_id'], ['mata_pelajaran.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jadwal_kelas_id'), 'jadwal', ['kelas_id'], unique=False)
    op.create_table('nilai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('mata_pelajaran_id', sa.Integer(), nullable=False),
    sa.Column('guru_id', sa.Integer(), nullable=False),
    sa.Column('jenis', sa.Enum('TUGAS', 'UH', 'UTS', 'UAS', name='jenis_nilai_enum'), nullable=False),
    sa.Column('nilai', sa.Float(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('tahun_ajaran', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['guru_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mata_pelajaran_id'], ['mata_pelajaran.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['siswa_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nilai_siswa_id'), 'nilai', ['siswa_id'], unique=False)
    op.create_table('parent_child',
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('student_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_user_id', 'student_user_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PENGUMUMAN', 'BERITA', 'GALERI', name='post_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('parent_child')
    op.drop_index(op.f('ix_nilai_siswa_id'), table_name='nilai')
    op.drop_table('nilai')
    op.drop_index(op.f('ix_jadwal_kelas_id'), table_name='jadwal')
    op.drop_table('jadwal')
    op.drop_index(op.f('ix_absensi_siswa_id'), table_name='absensi')
    op.drop_table('absensi')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ppdb_registrations')
    op.drop_table('mata_pelajaran')
    op.drop_table('kelas')
    # ### end Alembic commands ###
