"""add video_url to posts

Revision ID: 8f47f51f1b2c
Revises: 4785d5541786
Create Date: 2026-07-05 15:05:04.098622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f47f51f1b2c'
down_revision: Union[str, None] = '4785d5541786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('video_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'video_url')
    # ### end Alembic commands ###
