"""add image_url to content_items

Revision ID: ff10468db1d0
Revises: 10489ade64f4
Create Date: 2026-07-05 20:49:28.366950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff10468db1d0'
down_revision: Union[str, None] = '10489ade64f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


content_items_table = sa.table(
    "content_items",
    sa.column("section", sa.String),
    sa.column("sort_order", sa.Integer),
    sa.column("icon", sa.String),
    sa.column("title", sa.String),
    sa.column("subtitle", sa.String),
    sa.column("description", sa.Text),
    sa.column("image_url", sa.String),
)

# "Foto Sekolah" on the Galeri page was hardcoded (3 SVG-illustration cards,
# no real photos yet) and got missed when the rest of the site's content was
# migrated to ContentItem - image_url is None here since there are no real
# photos yet, same as before this migration (falls back to an illustration
# on the frontend until an admin uploads a real one).
FOTO_SEKOLAH_ITEMS: list[dict] = [
    {"section": "foto_sekolah", "sort_order": 1, "icon": None, "title": "Ruang Kelas", "subtitle": None, "description": None, "image_url": None},
    {"section": "foto_sekolah", "sort_order": 2, "icon": None, "title": "Mushola Mini", "subtitle": None, "description": None, "image_url": None},
    {"section": "foto_sekolah", "sort_order": 3, "icon": None, "title": "Area Bermain", "subtitle": None, "description": None, "image_url": None},
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###

    op.bulk_insert(content_items_table, FOTO_SEKOLAH_ITEMS)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'image_url')
    # ### end Alembic commands ###
